feat: support automatic sharding
crdsonnet/kube-state-metrics-libsonnet pull request #1
Opened 2024-01-30 11:17 UTC by Duologic

Extend this library to run KSM in automatic sharding mode, open sourcing this config as used within Grafana Labs.

2024-02-07 21:22 UTC, logyball requested changes
Comment regarding the statefulset, it doesn't seem to get rendered into json and/or YAML as a k8s manifest as it stands

2024-02-07 21:22 UTC, logyball commented on kube-state-metrics/main.libsonnet
> +        statefulset:: {},
This doesn't seem to work for me.  When defining a KSM file like this:

```jsonnet

... 

    meta.environment.baseEnvironment(
      root.app,
      cluster,
      root.namespace,
      data={
        kube_state_metrics:
          local kubeStateMetricsVersion = (import './waves.libsonnet')[cluster.wave];
          ksm.new(namespace=root.namespace)
          + ksm.withAutomaticSharding(10)
          + ksm.withPriorityClass('critical'),
      }
    ),

  envs: meta.environment.generateEnvs(root.clusters, root.environment),
}

...

```

I get the following output:

```sh
❯ tk eval ksonnet/environments/kube-state-metrics-2/main.jsonnet -e <environment> | jq '.data.kube_state_metrics | keys'
[
  "config_map",
  "pdb",
  "rbac",
]
```

Meaning the STS just straight up doesn't show up.

I can rectify this by setting the STS in line 84 to a visible field:

```
statefulset: {}
```

and modifying the withPriorityClass function slightly:

```jsonnet
withPriorityClass(priorityClassName):: {
    deployment+:
      k.apps.v1.deployment.spec.template.spec.withPriorityClassName(priorityClassName),
    statefulset+: if super.statefulset == {} then {} else k.apps.v1.statefulSet.spec.template.spec.withPriorityClassName(priorityClassName),
  },
```

WDYT?

2024-02-08 08:51 UTC, Duologic commented on kube-state-metrics/main.libsonnet
> +        statefulset:: {},
I've done it differently, exposing the statefulset with `:::` when invoking `withAutomaticSharding`.

2024-02-08 16:56 UTC, logyball commented on kube-state-metrics/main.libsonnet
> +        statefulset:: {},
TIL about `:::`

2024-05-16 21:49 UTC, logyball approved these changes
LGTM! Nice work on this

2024-06-07 14:18 UTC, merged